---
title: "MA388 Sabermetrics AY26-2"
editor: 
  markdown: 
    wrap: sentence
---

#### Welcome to MA388 Sabermetrics for AY26-2.

Use the navigation menu above to access lesson materials.

#### Course Objectives. By the end of the semester, you should be able to:

-   Use the investigative process in statistics to answer research questions of interest in sabermetrics.

-   Use statistical software to obtain, prepare, summarize, visualize, and model complex data.

-   Identify and employ advanced statistical methods for estimation and prediction to answer questions in sabermetrics.

-   Draw appropriate conclusions from statistical analyses and communicate them to general audiences.

-   Appreciate the importance and limitations of statistical inquiry to answer questions of interest.

-   Be critical consumers of statistically based results and recognize whether reported results reasonably follow from the study and analysis conducted.
    Course Materials.

#### **Textbooks**:

-   Analyzing Baseball Data with R (Third Edition) by Marchi, Albert, and Baumer \
    The textbook authors have made this book available for free online at this [link](https://beanumber.github.io/abdwr3e/).

-   Understanding Sabermetrics (2nd Edition) by Costa, Huber, and Saccoman \
    This textbook will be provided to cadets by the instructor.
