---
title: "textbook summary"
format: html
editor: visual
---

-   [1  The Baseball Datasets](https://beanumber.github.io/abdwr3e/01-datasets.html)
    -   [1.1 Introduction](https://beanumber.github.io/abdwr3e/01-datasets.html#introduction)
    -   [1.2 The Lahman Database: Season-by-Season Data](https://beanumber.github.io/abdwr3e/01-datasets.html#sec-lahman)
    -   [1.3 Retrosheet Game-by-Game Data](https://beanumber.github.io/abdwr3e/01-datasets.html#sec-datasets_Retrosheet)
    -   [1.4 Retrosheet Play-by-Play Data](https://beanumber.github.io/abdwr3e/01-datasets.html#sec-retro_pbp)
    -   [1.5 Pitch-by-Pitch Data](https://beanumber.github.io/abdwr3e/01-datasets.html#pitch-by-pitch-data)
    -   [1.6 Player Movement and Off-the-Bat Data](https://beanumber.github.io/abdwr3e/01-datasets.html#player-movement-and-off-the-bat-data)
    -   [1.7 Data Used in this Book](https://beanumber.github.io/abdwr3e/01-datasets.html#data-used-in-this-book)
    -   [1.8 Summary](https://beanumber.github.io/abdwr3e/01-datasets.html#summary)
    -   [1.9 Further Reading](https://beanumber.github.io/abdwr3e/01-datasets.html#further-reading)
    -   [1.10 Exercises](https://beanumber.github.io/abdwr3e/01-datasets.html#exercises)
-   [2  Introduction to R](https://beanumber.github.io/abdwr3e/02-intro.html)
    -   [2.1 Introduction](https://beanumber.github.io/abdwr3e/02-intro.html#introduction)
    -   [2.2 Installing R and RStudio](https://beanumber.github.io/abdwr3e/02-intro.html#installing-r-and-rstudio)
    -   [2.3 The Tidyverse](https://beanumber.github.io/abdwr3e/02-intro.html#the-tidyverse)
    -   [2.4 Data Frames](https://beanumber.github.io/abdwr3e/02-intro.html#sec-df)
    -   [2.5 Vectors](https://beanumber.github.io/abdwr3e/02-intro.html#sec-vectors)
    -   [2.6 Objects and Containers in R](https://beanumber.github.io/abdwr3e/02-intro.html#sec-objectscontainers)
    -   [2.7 Collection of R Commands](https://beanumber.github.io/abdwr3e/02-intro.html#collection-of-r-commands)
    -   [2.8 Reading and Writing Data in R](https://beanumber.github.io/abdwr3e/02-intro.html#sec-data_import)
    -   [2.9 Packages](https://beanumber.github.io/abdwr3e/02-intro.html#sec-pkg)
    -   [2.10 Splitting, Applying, and Combining Data](https://beanumber.github.io/abdwr3e/02-intro.html#sec-split_apply)
    -   [2.11 Getting Help](https://beanumber.github.io/abdwr3e/02-intro.html#sec-gettinghelp)
    -   [2.12 Further Reading](https://beanumber.github.io/abdwr3e/02-intro.html#further-reading)
    -   [2.13 Exercises](https://beanumber.github.io/abdwr3e/02-intro.html#exercises)
-   [3  Graphics](https://beanumber.github.io/abdwr3e/03-graphics2.html)
    -   [3.1 Introduction](https://beanumber.github.io/abdwr3e/03-graphics2.html#introduction)
    -   [3.2 Character Variable](https://beanumber.github.io/abdwr3e/03-graphics2.html#character-variable)
    -   [3.3 Saving Graphs](https://beanumber.github.io/abdwr3e/03-graphics2.html#saving-graphs)
    -   [3.4 Numeric Variable: One-Dimensional Scatterplot and Histogram](https://beanumber.github.io/abdwr3e/03-graphics2.html#numeric-variable-one-dimensional-scatterplot-and-histogram)
    -   [3.5 Two Numeric Variables](https://beanumber.github.io/abdwr3e/03-graphics2.html#two-numeric-variables)
    -   [3.6 A Numeric Variable and a Factor Variable](https://beanumber.github.io/abdwr3e/03-graphics2.html#a-numeric-variable-and-a-factor-variable)
    -   [3.7 Comparing Ruth, Aaron, Bonds, and A-Rod](https://beanumber.github.io/abdwr3e/03-graphics2.html#sec-comparesluggers)
    -   [3.8 The 1998 Home Run Race](https://beanumber.github.io/abdwr3e/03-graphics2.html#sec-section5)
    -   [3.9 Further Reading](https://beanumber.github.io/abdwr3e/03-graphics2.html#further-reading)
    -   [3.10 Exercises](https://beanumber.github.io/abdwr3e/03-graphics2.html#exercises)
-   [4  The Relation Between Runs and Wins](https://beanumber.github.io/abdwr3e/04-pythagoras.html)
    -   [4.1 Introduction](https://beanumber.github.io/abdwr3e/04-pythagoras.html#introduction)
    -   [4.2 The Teams Table in the Lahman Database](https://beanumber.github.io/abdwr3e/04-pythagoras.html#the-teams-table-in-the-lahman-database)
    -   [4.3 Linear Regression](https://beanumber.github.io/abdwr3e/04-pythagoras.html#sec-LinearRegression)
    -   [4.4 The Pythagorean Formula for Winning Percentage](https://beanumber.github.io/abdwr3e/04-pythagoras.html#the-pythagorean-formula-for-winning-percentage)
    -   [4.5 How Many Runs for a Win?](https://beanumber.github.io/abdwr3e/04-pythagoras.html#sec-runswin)
    -   [4.6 Further Reading](https://beanumber.github.io/abdwr3e/04-pythagoras.html#further-reading)
    -   [4.7 Exercises](https://beanumber.github.io/abdwr3e/04-pythagoras.html#exercises)
-   [5  Value of Plays Using Run Expectancy](https://beanumber.github.io/abdwr3e/05-runsexpectancy.html)
    -   [5.1 The Run Expectancy Matrix](https://beanumber.github.io/abdwr3e/05-runsexpectancy.html#sec-matrix)
    -   [5.2 Runs Scored in the Remainder of the Inning](https://beanumber.github.io/abdwr3e/05-runsexpectancy.html#runs-scored-in-the-remainder-of-the-inning)
    -   [5.3 Creating the Matrix](https://beanumber.github.io/abdwr3e/05-runsexpectancy.html#sec-runsexpectancy)
    -   [5.4 Measuring Success of a Batting Play](https://beanumber.github.io/abdwr3e/05-runsexpectancy.html#sec-run-values)
    -   [5.5 José Altuve](https://beanumber.github.io/abdwr3e/05-runsexpectancy.html#jos%C3%A9-altuve)
    -   [5.6 Opportunity and Success for All Hitters](https://beanumber.github.io/abdwr3e/05-runsexpectancy.html#opportunity-and-success-for-all-hitters)
    -   [5.7 Position in the Batting Lineup](https://beanumber.github.io/abdwr3e/05-runsexpectancy.html#position-in-the-batting-lineup)
    -   [5.8 Run Values of Different Base Hits](https://beanumber.github.io/abdwr3e/05-runsexpectancy.html#sec-runvaluebasehit)
    -   [5.9 Value of Base Stealing](https://beanumber.github.io/abdwr3e/05-runsexpectancy.html#value-of-base-stealing)
    -   [5.10 Further Reading and Software](https://beanumber.github.io/abdwr3e/05-runsexpectancy.html#further-reading-and-software)
    -   [5.11 Exercises](https://beanumber.github.io/abdwr3e/05-runsexpectancy.html#exercises)
-   [6  Balls and Strikes Effects](https://beanumber.github.io/abdwr3e/06-pitchcount.html)
    -   [6.1 Introduction](https://beanumber.github.io/abdwr3e/06-pitchcount.html#introduction)
    -   [6.2 Hitter’s Counts and Pitcher’s Counts](https://beanumber.github.io/abdwr3e/06-pitchcount.html#sec-hit_pit_counts)
    -   [6.3 Behaviors by Count](https://beanumber.github.io/abdwr3e/06-pitchcount.html#behaviors-by-count)
    -   [6.4 Further Reading](https://beanumber.github.io/abdwr3e/06-pitchcount.html#further-reading)
    -   [6.5 Exercises](https://beanumber.github.io/abdwr3e/06-pitchcount.html#exercises)
-   [7  Catcher Framing](https://beanumber.github.io/abdwr3e/07-framing.html)
    -   [7.1 Introduction](https://beanumber.github.io/abdwr3e/07-framing.html#introduction)
    -   [7.2 Acquiring Pitch-Level Data](https://beanumber.github.io/abdwr3e/07-framing.html#acquiring-pitch-level-data)
    -   [7.3 Where Is the Strike Zone?](https://beanumber.github.io/abdwr3e/07-framing.html#where-is-the-strike-zone)
    -   [7.4 Modeling Called Strike Percentage](https://beanumber.github.io/abdwr3e/07-framing.html#modeling-called-strike-percentage)
    -   [7.5 Modeling Catcher Framing](https://beanumber.github.io/abdwr3e/07-framing.html#sec-catcher-framing)
    -   [7.6 Further Reading](https://beanumber.github.io/abdwr3e/07-framing.html#further-reading)
    -   [7.7 Exercises](https://beanumber.github.io/abdwr3e/07-framing.html#exercises)
-   [8  Career Trajectories](https://beanumber.github.io/abdwr3e/08-trajectories.html)
    -   [8.1 Introduction](https://beanumber.github.io/abdwr3e/08-trajectories.html#introduction)
    -   [8.2 Mickey Mantle’s Batting Trajectory](https://beanumber.github.io/abdwr3e/08-trajectories.html#sec-mantle)
    -   [8.3 Comparing Trajectories](https://beanumber.github.io/abdwr3e/08-trajectories.html#sec-comparison)
    -   [8.4 General Patterns of Peak Ages](https://beanumber.github.io/abdwr3e/08-trajectories.html#sec-general)
    -   [8.5 Trajectories and Fielding Position](https://beanumber.github.io/abdwr3e/08-trajectories.html#sec-fielding)
    -   [8.6 Further Reading](https://beanumber.github.io/abdwr3e/08-trajectories.html#further-reading)
    -   [8.7 Exercises](https://beanumber.github.io/abdwr3e/08-trajectories.html#exercises)
-   [9  Simulation](https://beanumber.github.io/abdwr3e/09-simulation.html)
    -   [9.1 Introduction](https://beanumber.github.io/abdwr3e/09-simulation.html#introduction)
    -   [9.2 Simulating a Half Inning](https://beanumber.github.io/abdwr3e/09-simulation.html#sec-markovchain)
    -   [9.3 Simulating a Baseball Season](https://beanumber.github.io/abdwr3e/09-simulation.html#sec-bradleyterry)
    -   [9.4 Further Reading](https://beanumber.github.io/abdwr3e/09-simulation.html#further-reading)
    -   [9.5 Exercises](https://beanumber.github.io/abdwr3e/09-simulation.html#exercises)
-   [10  Exploring Streaky Performances](https://beanumber.github.io/abdwr3e/10-streak.html)
    -   [10.1 Introduction](https://beanumber.github.io/abdwr3e/10-streak.html#introduction)
    -   [10.2 The Great Streak](https://beanumber.github.io/abdwr3e/10-streak.html#sec-joed)
    -   [10.3 Streaks in Individual At-Bats](https://beanumber.github.io/abdwr3e/10-streak.html#sec-individual)
    -   [10.4 Local Patterns of Statcast Launch Velocity](https://beanumber.github.io/abdwr3e/10-streak.html#sec-woba)
    -   [10.5 Further Reading](https://beanumber.github.io/abdwr3e/10-streak.html#further-reading)
    -   [10.6 Exercises](https://beanumber.github.io/abdwr3e/10-streak.html#exercises)
-   [11  Using a Database to Compute Park Factors](https://beanumber.github.io/abdwr3e/11-sql.html)
    -   [11.1 Introduction](https://beanumber.github.io/abdwr3e/11-sql.html#introduction)
    -   [11.2 Installing MySQL and Creating a Database](https://beanumber.github.io/abdwr3e/11-sql.html#sec-startMySQL)
    -   [11.3 Connecting R to MySQL](https://beanumber.github.io/abdwr3e/11-sql.html#connecting-r-to-mysql)
    -   [11.4 Filling a MySQL Game Log Database from R](https://beanumber.github.io/abdwr3e/11-sql.html#sec-gamelog)
    -   [11.5 Querying Data from R](https://beanumber.github.io/abdwr3e/11-sql.html#querying-data-from-r)
    -   [11.6 Building Your Own Baseball Database](https://beanumber.github.io/abdwr3e/11-sql.html#sec-owndb)
    -   [11.7 Calculating Basic Park Factors](https://beanumber.github.io/abdwr3e/11-sql.html#sec-parkfactors)
    -   [11.8 Further Reading](https://beanumber.github.io/abdwr3e/11-sql.html#further-reading)
    -   [11.9 Exercises](https://beanumber.github.io/abdwr3e/11-sql.html#exercises)
-   [12  Working with Large Data](https://beanumber.github.io/abdwr3e/12-large.html)
    -   [12.1 Introduction](https://beanumber.github.io/abdwr3e/12-large.html#introduction)
    -   [12.2 Acquiring a Year’s Worth of Statcast Data](https://beanumber.github.io/abdwr3e/12-large.html#sec-statcast-year)
    -   [12.3 Storing Large Data Efficiently](https://beanumber.github.io/abdwr3e/12-large.html#storing-large-data-efficiently)
    -   [12.4 Performance Comparison](https://beanumber.github.io/abdwr3e/12-large.html#sec-performance)
    -   [12.5 Launch Angles and Exit Velocities, Revisited](https://beanumber.github.io/abdwr3e/12-large.html#sec-launch_angle)
    -   [12.6 Further Reading](https://beanumber.github.io/abdwr3e/12-large.html#further-reading)
    -   [12.7 Exercises](https://beanumber.github.io/abdwr3e/12-large.html#exercises)
-   [13  Home Run Hitting](https://beanumber.github.io/abdwr3e/13-homeruns.html)
    -   [13.1 Introduction](https://beanumber.github.io/abdwr3e/13-homeruns.html#introduction)
    -   [13.2 Exploring a Season of Home Run Hitting](https://beanumber.github.io/abdwr3e/13-homeruns.html#sec-hr_exploring)
    -   [13.3 Comparing Home Run Hitting in the 2021 and 2023 Seasons](https://beanumber.github.io/abdwr3e/13-homeruns.html#sec-hr_changes)
    -   [13.4 Further Reading](https://beanumber.github.io/abdwr3e/13-homeruns.html#further-reading)
    -   [13.5 Exercises](https://beanumber.github.io/abdwr3e/13-homeruns.html#exercises)
-   [14  Making a Scientific Presentation using Quarto](https://beanumber.github.io/abdwr3e/14-quarto.html)
    -   [14.1 Introduction to Slides in Quarto](https://beanumber.github.io/abdwr3e/14-quarto.html#introduction-to-slides-in-quarto)
    -   [14.2 Example: Jim’s Presentation on Home Run Hitting](https://beanumber.github.io/abdwr3e/14-quarto.html#sec-slides)
    -   [14.3 Alternative Output Formats](https://beanumber.github.io/abdwr3e/14-quarto.html#sec-beamer)
    -   [14.4 Further Reading](https://beanumber.github.io/abdwr3e/14-quarto.html#further-reading)
    -   [14.5 Exercises](https://beanumber.github.io/abdwr3e/14-quarto.html#exercises)
-   [15  Using Shiny for Baseball Applications](https://beanumber.github.io/abdwr3e/15-shiny.html)
    -   [15.1 Introduction](https://beanumber.github.io/abdwr3e/15-shiny.html#introduction)
    -   [15.2 Comparing Two Pitcher Trajectories](https://beanumber.github.io/abdwr3e/15-shiny.html#sec-function)
    -   [15.3 Creating the Shiny App](https://beanumber.github.io/abdwr3e/15-shiny.html#sec-creating_shiny)
    -   [15.4 Sharing the App](https://beanumber.github.io/abdwr3e/15-shiny.html#sec-sharing_shiny)
    -   [15.5 Tips for Getting Started Making Apps](https://beanumber.github.io/abdwr3e/15-shiny.html#sec-shiny_tips)
    -   [15.6 Further Reading](https://beanumber.github.io/abdwr3e/15-shiny.html#further-reading)
    -   [15.7 Exercises](https://beanumber.github.io/abdwr3e/15-shiny.html#exercises)
-   Appendices
    -   [A  Retrosheet Files Reference](https://beanumber.github.io/abdwr3e/A_retrosheet.html)
    -   [B  Historical Notes on PITCHf/x Data](https://beanumber.github.io/abdwr3e/B_mlbam.html)
    -   [C  Statcast Data Reference](https://beanumber.github.io/abdwr3e/C_statcast.html)
    -   [References](https://beanumber.github.io/abdwr3e/99-references.html)

Problem Set descriptions:

1.  Data set exploration and dplyr functions

2.  Plotting career trajectories

3.  Regression of Win% vs run differential

4.  Sacrifice Bunt
